void rusText(){
  tMes = "Моей любимой Зающке!!!";
  tNow = "сейчас";
  tPress = "ммРс";
  tSpeed = "м/с";
  tMin = "мин.";
  tCurr = "Сегодня";
  tTom = "Завтра";
  tYour = "Ваш";
  tPoint = "Подключитесь к точке доступа WiFi-Clock и введите в браузере адрес: 192.168.4.1         ";
  tWarsaw = "Варшава";
  tKrivoy = "Кривой Рог";
  tKyiv = "Киев";
  tOdessa = "Одесса";
  tDnepr = "Днепр";
  tCherkassy = "Черкасы";
  tLviv = "Львов";
  tKherson = "Херсон";
  tNikolaev = "Николаев";
  tZaporozhye = "Запорожье";
  tKharkiv = "Харков";
  tDonetsk = "Донецк";
  tLugansk = "Луганск";
  tPoltava = "Полтава";
  tSumy = "Сумми";
  tChernigov = "Чернигов";
  tZhytomyr = "Житомир";
  tRivne = "Ровно";
  tKropivnitsky = "Кропивницкий";
  tUman = "Умань";
  tVinnitsa = "Винница";
  tKhmelnitsky = "Хмельницкий";
  tTernopil = "Тернополь";
  tLutsk = "Луцк";
  tKovel = "Ковель";
  tChernivtsi = "Черновцы";
  tIvano = "Ивано-Франковск";
  tStry = "Стрый";
  tMukachevo = "Мукачево";
  tUzhgorod = "Ужгород";
  tCzenstochowa = "Ченстохова";
  tKrakow = "Краков";
  tLublinec = "Люблинец";
  tJanuary = "января";
  tFebruary = "февраля";
  tMarch = "марта";
  tApril = "апреля";
  tMay = "мая";
  tJune = "июня";
  tJuly = "июля";
  tAugust = "августа";
  tSeptember = "сентября";
  tOctober = "октября";
  tNovember = "ноября";
  tDecember = "декабря";
  tMonday = "Понедельник";
  tTuesday = "Вторник";
  tWednesday = "Среда";
  tThursday = "Четверг";
  tFriday = "Пятница";
  tSaturday = "Суббота";
  tSunday = "Воскресенье";

  tWeatrNot = "   Нет обновления погоды более 6 часов!!!   ";
  tWeatrTN = "нет обновления погоды - ";
  if(printCom) {
    printTime();
    Serial.println("Text RUS.");
  }
  weatherLang = "ru";
}

