void ukrText(){
  tMes = "Моїй коханій Зайченяткі";
  tNow = "зараз";
  tPress = "ммРс";
  tSpeed = "м/с";
  tMin = "хв.";
  tCurr = "Сьогодні";
  tTom = "Завтра";
  tYour = "Ваш";
  tPoint = "Підключіться до точки доступу WiFi-Clock і введіть в браузері адресу: 192.168.4.1       ";
  tWarsaw = "Варшава";
  tKrivoy = "Кривий Ріг";
  tKyiv = "Київ";
  tOdessa = "Одеса";
  tDnepr = "Дніпро";
  tCherkassy = "Черкаси";
  tLviv = "Львів";
  tKherson = "Херсон";
  tNikolaev = "Миколаїв";
  tZaporozhye = "Запоріжжя";
  tKharkiv = "Харків";
  tDonetsk = "Донецьк";
  tLugansk = "Луганськ";
  tPoltava = "Полтава";
  tSumy = "Суми";
  tChernigov = "Чернігів";
  tZhytomyr = "Житомир";
  tRivne = "Рівне";
  tKropivnitsky = "Кропивницький";
  tUman = "Умань";
  tVinnitsa = "Вінниця";
  tKhmelnitsky = "Хмельницький";
  tTernopil = "Тернопіль";
  tLutsk = "Луцьк";
  tKovel = "Ковель";
  tChernivtsi = "Чернівці";
  tIvano = "Івано-Франківськ";
  tStry = "Стрий";
  tMukachevo = "Мукачево";
  tUzhgorod = "Ужгород";
  tCzenstochowa = "Ченстохова";
  tKrakow = "Краков";
  tLublinec = "Люблінець";
  tJanuary = "січня";
  tFebruary = "лютого";
  tMarch = "березня";
  tApril = "квітня";
  tMay = "травня";
  tJune = "червня";
  tJuly = "липня";
  tAugust = "серпня";
  tSeptember = "вересня";
  tOctober = "жовтня";
  tNovember = "листопада";
  tDecember = "грудня";
  tMonday = "Понеділок";
  tTuesday = "Вівторок";
  tWednesday = "Середа";
  tThursday = "Четвер";
  tFriday = "П'ятниця";
  tSaturday = "Субота";
  tSunday = "Неділя";

  tWeatrNot = "   Немає оновлень погоди більше 6 годин!!!   ";
  tWeatrTN = "немає оновлень погоди - ";
    if(printCom) {
    printTime();
    Serial.println("Text UKR.");
  }
  weatherLang = "uk";
}
