void enText(){
  tMes = "To my beloved Zayushke !!!";
  tNow = "now";
  tPress = "mmРс";
  tSpeed = "m/s";
  tMin = "min.";
  tTom = "Tomorrow";
  tKurs = "Course Privat24";
  tSale = "Purchase/Sale.";
  tYour = "Your";
  tPoint = "Connect to the WiFi-Clock access point and enter in the browser the address: 192.168.4.1         ";
  tWarsaw = "Warsaw";
  tKrivoy = "Krivoy Rog";
  tKyiv = "Kiev";
  tOdessa = "Odessa";
  tDnepr = "Dnieper";
  tCherkassy = "Cherkasy";
  tLviv = "Lviv";
  tKherson = "Kherson";
  tNikolaev = "Mykolaiv";
  tZaporozhye = "Zaporozhye";
  tKharkiv = "Harkov";
  tDonetsk = "Donetsk";
  tLugansk = "Lugansk";
  tPoltava = "Poltava";
  tSumy = "Summy";
  tChernigov = "Chernigov";
  tZhytomyr = "Zhitomir";
  tRivne = "Rivne";
  tKropivnitsky = "Kropiwnicki";
  tUman = "Uman";
  tVinnitsa = "Vinnitsa";
  tKhmelnitsky = "Khmelnytskyi";
  tTernopil = "Ternopil";
  tLutsk = "Lutsk";
  tKovel = "Kovel";
  tChernivtsi = "Chernivtsi";
  tIvano = "Ivano-Frankivsk";
  tStry = "Stryj";
  tMukachevo = "Mukacheve";
  tUzhgorod = "Uzhhorod";
  tCzenstochowa = "Czestochova";
  tKrakow = "Krakov";
  tLublinec = "Lubliniec";
  tJanuary = "January";
  tFebruary = "February";
  tMarch = "Martha";
  tApril = "April";
  tMay = "May";
  tJune = "June";
  tJuly = "July";
  tAugust = "August";
  tSeptember = "September";
  tOctober = "October";
  tNovember = "November";
  tDecember = "December";
  tMonday = "Monday";
  tTuesday = "Tuesday";
  tWednesday = "Wednesday";
  tThursday = "Thursday";
  tFriday = "Friday";
  tSaturday = "Saturday";
  tSunday = "Sunday";
  tWeatrNot = "   There is no weather update for more than 6 hours !!!   ";
  tWeatrTN = "no weather updates - ";
  if(printCom) {
    printTime();
    Serial.println("Text EN.");
  }
}

